language: java

jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
  - $HOME/.m2
  
install: echo 'Skipping separate install phase'

before_script:
 - chmod +x dockerPush.sh
 - mv ./src/main/resources/application.properties_example ./src/main/resources/application.properties
 - mv ./src/main/resources/config.json_example ./src/main/resources/config.json
 - export TZ=Europe/Amsterdam

script:
  - mvn install -Dmaven.javadoc.skip=true -B -V
  - jar -xvf ./target/zds-to-zgw.jar
  - docker-compose up --build
  - curl http://localhost:8080
  - docker-compose down
  - ./dockerPush.sh

